### ISSUE TITLE
"TypeError: Cannot read property 'replace' of undefined" in Umbraco 7.1.2+

### ISSUE THREAD

**Issue by MarcStoecker** [mindrevolution/SirTrevor-for-Umbraco#12]
Probably related to the change in asset loader (lazyload.js instead of yepnope.js)?

**Comment by MarcStoecker** [comment]
Looks like the textfield isn't getting it's value bound by ng "fast enough". Because the old loader did (technically unneccessary) network roundtrips (browser cached, though) for the given assets, this extra latency was probably covering that (underlying) problem.

I wasn't able to find a solution with viewContentLoaded or includeContentLoaded for instance. For now a workaround is implemented that's wasting 10ms and asyncs the editor load.

Anyone has a tipp? :)

**Comment by MarcStoecker** [comment]
I have tested the workaround with some blank 7.1.3 installs as well as an updated site and the problem is solved. I'd say we just keep it this way for now and I will pack a service release 0.6.2 and put it on the package page on our.

**Comment by protherj** [comment]
Is this fix in the latest package on Our?  I'm using Umbraco 7.1.4 and I'm seeing this issue intermittently.

**Comment by MarcStoecker** [comment]
Yes, should be fixed. I'll test with 7.1.4 plus the 0.6.2. package from Our.

**Comment by protherj** [comment]
OK, I'll make sure we're on the latest version of Sir Trevor
