### ISSUE TITLE
imageHelper is deprecated, not working with Image Cropper on media in 7.2+

### ISSUE THREAD

**Issue by MarcStoecker** [mindrevolution/SirTrevor-for-Umbraco#18]
Need to switch over to mediaHelper: http://umbraco.github.io/Belle/#/api/umbraco.services.mediaHelper

**Comment by protherj** [comment]
Is this why the images don't show up in Sir Trevor?

**Comment by MarcStoecker** [comment]
Yes, most likely. We're currently preparing for a new 0.7.0 beta release, if you're not in production yet it will probably be best to wait for it. Otherwise you'll need to fetch everything from the repo and pull it together.

**Comment by protherj** [comment]
Do you have an ETA for 0.7.0?  We're not in Production yet, but we are in Content entry so it would be helpful.

**Comment by MarcStoecker** [comment]
I'll try my best to have it out by next week. We are in the same situation, so my team's putting pressure on me as well... ;-)

**Comment by MarcStoecker** [comment]
To clarify: Unfortunatly it's not in the 0.6.2 package - sorry. Best to got with the upcoming 0.7 package.

**Comment by MarcStoecker** [comment]
0.7.0 beta is here -- http://our.umbraco.org/projects/backoffice-extensions/sir-trevor
