### ISSUE TITLE
Parsing content

### ISSUE THREAD

**Issue by tommyw** [mindrevolution/SirTrevor-for-Umbraco#2]
Do you have any recommendations on how to parse the Sir Trevor JSON content in Razor? For example, I have this content - I can deserialize and manually parse/render, but is there anything more simple out there?

{
  "data": [
    {
      "type": "text",
      "data": {
        "text": "**For this intro**, blah blah blah.\n\nYour bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown."
      }
    },
    {
      "type": "video",
      "data": {
        "source": "vimeo",
        "remote_id": "81607081"
      }
    }
  ]
}

**Comment by MarcStoecker** [comment]
SirTrevor is saving text blocks in Markdown format. You can use any of the .NET libraries available to render it into HTML. Here are the most popular ones: http://www.nuget.org/packages?q=markdown

We use MarkdownDeep at mindrevolution. I'm thinking about bundling some razor snippets with the package. Would that be of help? What do you think?

**Comment by MarcStoecker** [comment]
You can easily iterate over the blocks with Umbraco 7. Here's a minimal sample:

``` @{
    foreach(dynamic block in CurrentPage.blocks.data) {     
        <h3>@block.type</h3>
        <p>@block.data.text</p>
    }
}
```

**Comment by MarcStoecker** [comment]
**Update**
If you upgrade your installation to the new 0.5.0 (or newer) version, I've included a simple sample Razor template and a Razor Markdown helper there, that does all the output (for localLinks as well).

[Download it at our.umbraco.org](http://our.umbraco.org/projects/backoffice-extensions/sir-trevor)
