### ISSUE TITLE
Line breaks in text block

### ISSUE THREAD

**Issue by wayferer** [mindrevolution/SirTrevor-for-Umbraco#20]
Apologies if this is the wrong place to ask but I am using the default text block that comes with Sir Trevor but I can't figure out how to add linebreaks in the back office so they will render correctly in the front-end. Here is the snippet I am using to get the content.

```
@foreach(dynamic block in @CurrentPage.Content.data){
                switch((string)block.type)
                {
                    case "heading":
                    string heading = block.data.text;
                    <h2>@heading</h2>
                    break;
                    case "text":
                    string text = block.data.text;
                    @SirTrevor.Markdown(text)
                    break;
                    case "list":
                    string list = block.data.text;
                    @SirTrevor.Markdown(list)
                    break;
                }
            }
```

Thanks in advance.

**Comment by MarcStoecker** [comment]
In a "br"-way? Add two or more spaces at the end of the line (see Markup syntax)

**Comment by wayferer** [comment]
Thank you.

**Comment by MarcStoecker** [comment]
You're welcome. Please use the community discussion board for these type of questions in the future: http://our.umbraco.org/projects/backoffice-extensions/sir-trevor/community-board

On GitHub we focus on the dev sid of things :)

**Comment by wayferer** [comment]
Apologies, will do :)

**Comment by MarcStoecker** [comment]
I think everybody profits, if these type of questions are in one place at our.umbraco.org, so everybody knows where to look for answers. But certainly sometimes it's hard to judge if it's a bug or a user error or such. However, no worries! :)

**Comment by wayferer** [comment]
Very true. Would it be useful if I created a post there and linked back here? To be honest it should have clicked for me to use Markup syntax given that's what the output is so might not me that useful.

**Comment by MarcStoecker** [comment]
Honestly, I was asked that many times, so you're definately not alone with that question. Also, I'm undecided if I should see that as a usability problem. I think it is one, to an extend. If you like, just (re)post it on our as a question and I can answer and document it this way, I will answer then.

**Comment by wayferer** [comment]
Done http://our.umbraco.org/projects/backoffice-extensions/sir-trevor/community-board/54065-Line-breaks-in-text-block

**Comment by MarcStoecker** [comment]
Thanks. Answered. :)

**Comment by MarcStoecker** [comment]
If you find the time, could you please mark that as answered ("green") on the Our forum? Thanks! :)

**Comment by wayferer** [comment]
Done :) Thanks again!
