### ISSUE TITLE
Quote returns "> " before quote text

### ISSUE THREAD

**Issue by karltynan** [mindrevolution/SirTrevor-for-Umbraco#25]
When viewing the quote text, it is prefixed with "> " before the output.

**Comment by MarcStoecker** [comment]
Yes, this is due to the Markdown syntax used. In Markdown ">" is used to indicate a quote. Just use the helper SirTrevor.Markdown(text) to have it transformed to HTML.

**Comment by MarcStoecker** [comment]
Just realized, that this is missing from the demo template as well, thanks for bringing that up!

**Comment by karltynan** [comment]
Excellent, although that means you would have to inject the cite into the markdown, or escape the blockquote from markdown?

**Comment by MarcStoecker** [comment]
True, depending on the situation you would need to inject the cite into the quote (depending on markup/css/etc.). Not (always) ideal.
