### ISSUE TITLE
Checkboxes are re-selected when editing a Sir Trevor datatype

### ISSUE THREAD

**Issue by karltynan** [mindrevolution/SirTrevor-for-Umbraco#27]
If you select a few blocks in the Sir Trevor datatype, leave then come back, all checkboxes are now selected.

**Comment by MarcStoecker** [comment]
That surely shouldn't happen. You are using 0.7.0 beta I suppose?

**Comment by karltynan** [comment]
Umbraco 7.1.4 - cannot reproduce it now, sorry...

**Comment by MarcStoecker** [comment]
No worries.
