### ISSUE TITLE
Tried to install it in u 7.01 - what am I missing?

### ISSUE THREAD

**Issue by joeriks** [mindrevolution/SirTrevor-for-Umbraco#3]
Hi! Thanks for creating this!

However - I tried to install it in an upgraded 7.01 site. But do not get the editor to show up. Am I missing something? 

The property shows up in doc type editor and all the files seem to be there in app_plugins. But the editor is not rendered - and when I check the html all I see is ReadOnlyValueController where I expected to see SirTrevorController:

```
<div class="controls controls-row" ng-transclude="">

    <div ng-include="propertyEditorView" model="property" class="ng-scope"><div class="umb-editor umb-readonlyvalue ng-scope ng-binding" ng-controller="Umbraco.PropertyEditors.ReadOnlyValueController">

</div>
```

**Comment by MarcStoecker** [comment]
Are you just seeing an empty textarea or a textarea with i.e. "mode.value" or something linke that in it? Could you share a screenshot? Also be sure to Shift-Reload the backend.

**Comment by joeriks** [comment]
Its just an empty div. Im thinking it might be with my upgrade - I'm about to try Sir Trevor on a vanilla 7.01 installation next.

**Comment by MarcStoecker** [comment]
Anything in the console?

**Comment by joeriks** [comment]
No, I just tried on a vanilla 7.0.1 aswell - same prob, hm did they change
something in the package system?

[image: Infogad bild 1]

2013/12/20 Marc Stöcker notifications@github.com

> Anything in the console?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mindrevolution/SirTrevor-for-Umbraco/issues/3#issuecomment-31019317
> .

![image](https://f.cloud.github.com/assets/658329/1791844/d0751724-6994-11e3-9620-daf04c852a4f.png)

## 

Jonas Eriksson
Programenta
Tel 0650-13750, E-post jonas@programenta.se

**Comment by joeriks** [comment]
Its obviously something with the installer, I get "The property editor with alias Sir.Trevor does not exist" in the tracelog - and I cant install the other v7 package I tried either in 7.0.1 ("Matrix" aka "There is no spoon"). Will send a report to the umbraco issue tracker.

**Comment by joeriks** [comment]
Gah - i simply needed to restart it (touched web.config). Not used to need to do that. A quirk in v7?

**Comment by MarcStoecker** [comment]
Glad you got it working!

Yes, that's a v7 quirk. I'll check if a complete reload of the backend would be enough? Due to copying the markdown assembly to /bin the app pool should have been restarted already anyways? So more likely it's just the new backend not picking it up. So, in a way this issue is still an issue.

**Comment by MarcStoecker** [comment]
Looks like Warren Buckley already reported this bug on the issue tracker: http://issues.umbraco.org/issue/U4-3827
