### ISSUE TITLE
Text formatting and linking no longer working in 0.6.0 BETA

### ISSUE THREAD

**Issue by MarcStoecker** [mindrevolution/SirTrevor-for-Umbraco#5]

**Comment by FerdyHoefakker** [comment]
This might be a silly question, but is this a Sir Trevor bug, or a bug in the Umbraco package?

**Comment by MarcStoecker** [comment]
No silly question at all! :)

Actually it's indeed a SirTrevor bug, not a package/plugin bug:
https://github.com/madebymany/sir-trevor-js/commit/c2c543efdcd135d210cd1b0b9c7e72c8d1069165

I will update the package the next days as a 0.6.0 final.

**Comment by MarcStoecker** [comment]
Fixed in 0.6.0
our.umbraco.org/projects/backoffice-extensions/sir-trevor
