### ISSUE TITLE
Saving data from custom blocks

### ISSUE THREAD

**Issue by FerdyHoefakker** [mindrevolution/SirTrevor-for-Umbraco#8]
Hello, 

I am trying to make a custom block, but whenever I save and publish the page it is on, my custom block disappears. Most likely I am missing something silly (as usual). But if anyone could take a look, that'd be much appreciated.

SirTrevor.Blocks.CustomBlock= (function () {

```
var template = '<div class="st-text-block" contenteditable="true"></div>';

return SirTrevor.Block.extend({

    type: "CustomBlock_info",

    icon_name: 'CustomBlock_info',

    editorHTML: function () {
        return _.template(template, this);
    },

    loadData: function (data) {
        this.getTextBlock().html(SirTrevor.toHTML(data.text, this.type));
    },

    onBlockRender: function () {
        console.log("lalala");
    },
    toData: function () {
        this.setData(this.$('.st-info-block').val());
    },
    toMarkdown: function (markdown) {
        return markdown;
    }
```

});

})();

**Comment by MarcStoecker** [comment]
Can you read the block and it's data from the console after you added it? You probably checked that, but if it isn't in the JSON at save, it's lost, sure. At first look your block's code looks like derived from the standard markup block, so that should work.

**Comment by MarcStoecker** [comment]
Already tried to generate a data object first (in toData) and assign the value to a property and save the object then? Like so ...

```
var dataObj = {};
dataObj.info = this.$('.st-info-block').val();
this.setData(dataObj);
```

**Comment by MarcStoecker** [comment]
Ferdy, I will be closing this issue shortly because it's most likely not linked to the Sir Trevor for Umbraco plugin but a general problem with the block and the Sir Trevor project's page would be a better option to seek help: https://github.com/madebymany/sir-trevor-js/issues

Feel free to get back to me if this reveals as plugin related! Thanks.

**Comment by FerdyHoefakker** [comment]
Makes sense. Though I tried what you suggested and now whenever I save a sir trevor instance it deletes the whole thing.
