### ISSUE TITLE
External links return undefined

### ISSUE THREAD

**Issue by FerdyHoefakker** [mindrevolution/SirTrevor-for-Umbraco#9]
When I add an external link to the text, it will render as: 

&lt;a href="/{localLink:undefined}"&gt;text&lt;/a&gt;

Internal links render correctly.

**Comment by MarcStoecker** [comment]
Good find!

**Comment by MarcStoecker** [comment]
Hey Ferdy, I'd be very cool if you could test and confirm if the current build fixed this problem for you as well.

You just need to override the link formatter (/App_Plugins/SirTrevor/formatters/umbraco.min.js + non-min and map if you care). Let me know if you have trouble testing. Thanks!

**Comment by FerdyHoefakker** [comment]
Hey Marc,

I'm not in the office tomorrow, but I'll go check it out when I get back on Tuesday.

-Ferdy

Date: Sun, 18 May 2014 07:50:44 -0700

**Comment by MarcStoecker** [comment]
Great, thanks for your help!

**Comment by FerdyHoefakker** [comment]
Marc,

Is it correct that I am now getting a simple javascript box to enter an url? It now shows the url correctly. However,it seems that internal links made with the umbraco url thing now no longer work.

**Comment by MarcStoecker** [comment]
No, that shouldn't be the case. It looks like the Umbraco formatter for links isn't called at all? Have you retrieved these files from the repo and overridden your local ones? https://github.com/mindrevolution/SirTrevor-for-Umbraco/tree/master/src/App_Plugins/SirTrevor/formatters

Just asking to make sure ... :)

**Comment by FerdyHoefakker** [comment]
Yeah, I am getting a simple javascript pop-up and nothing more.

**Comment by MarcStoecker** [comment]
Anything on the console?

**Comment by FerdyHoefakker** [comment]
Right. I'm an idiot. I somehow didn't overwrite the files correctly. It works now, great! Only nitpick: 

If I enter an external url, it won't remember it when I try to edit it.

**Comment by MarcStoecker** [comment]
No worries. Glad it works! :)

It's not perfect in every respect right now, but I will try to improve it over time. Would you be so kind and add that "nitpick" (remembering external URL on edit) as an issue, so we can keep track of it?

**Comment by FerdyHoefakker** [comment]
No problem. Will add it now.

**Comment by MarcStoecker** [comment]
Thanks!
